### ISSUE TITLE
Random bug I found while testing

### ISSUE THREAD

**Issue by BlueFinnTuna** [F1nn1125/CardPricer#2]
After finished inputting cards, code throws:
```
Traceback (most recent call last):
  File "PATH", line 79, in <module>
    main()
  File "PATH", line 64, in main    
    total_price = round(sum(card_details.values()), 2)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

This bug seems to happen at random so for now just creating an issue,
will update as I learn more about it.

**Comment by BlueFinnTuna** [comment]
Nvm this somehow still exists it seems to just happen at random so I'm not sure if I'll ever find a solution.
